vmps:
  - name: Utrogestan 100mg # Common but historic shortages
    snomed_code: "11763511000001102"
  - name: Estriol 0.1% cream  # SSP as of 2022
    snomed_code: "41896911000001100"
  - name: Paracetamol 500 caps # OTC - possibly interesting
    snomed_code: "42109411000001106"
  - name: Methylphenidate 27mg modified-release tabs
    snomed_code: "36124211000001103"  # Current shortages
  - name: Ramipril 2.5mg caps # control - very common
    snomed_code: "42381411000001102"
  - name: Atorvastatin 20mg tabs # control - very common
    snomed_code: "39733011000001106"
  - name: Lisedexamfetamine 20mg caps # known shortage
    snomed_code: "42013311000001109"
  - name: Lisedexamfetamine 30mg caps # known shortage
    snomed_code: "42013411000001102"
  - name: Cefalexin 500mg capsules
    snomed_code: "39694811000001102"  # chromic, serious and rare 
  - name: Cefalexin 500mg tablets
    snomed_code: "39735911000001106"  # interchangeable clinically with prev but obvs a pharmacist can't change so they are two to look at together
  - name: Concerta XL 36mg tablets
    snomed_code: "36124511000001100"  # Concerta XL generally reported in shortage as of Sep 2024

