vmps:
  - name: Utrogestan 100mg # Common but historic shortages
    snomed_code: "11763511000001102"
  - name: Paracetamol 500 caps # OTC - possibly interesting
    snomed_code: "42109411000001106"
  - name: Methylphenidate 27mg modified-release tabs
    snomed_code: "36124211000001103"  # Current shortages
  - name: Ramipril 2.5mg caps # control - very common
    snomed_code: "42381411000001102"
  - name: Atorvastatin 20mg tabs # control - very common
    snomed_code: "39733011000001106"
  - name: Lisedexamfetamine 20mg caps # known shortage
    snomed_code: "42013311000001109"
  - name: Lisedexamfetamine 30mg caps # known shortage
    snomed_code: "42013411000001102"

